---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bitwarden-sm
  namespace: flux-system
spec:
  targetNamespace: sm-operator
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/sm-operator/bitwarden-sm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: netcluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
