---
keys:
  - &user_kleidi age15f6mcwjjav4z757kad8wksalgemael364wwxz7qsral5gmjzmd2qre78d5
  - &machine_radon age1zqz5cpgwe2fcl5dhxfcfdj52ljq89t8entc2lsyd6qzct2suevxsnnw4r2

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_kleidi
          - *machine_radon
