---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: ./deploy
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
  patches:
    - patch: |-
        kind: ConfigMap
        apiVersion: v1
        metadata:
          name: local-path-config
          namespace: local-path-storage
        data:
          config.json: |-
            {
                    "nodePathMap":[
                    {
                            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                            "paths":["/var/local-path-provisioner"]
                    }
                    ]
            }
    - patch: |-
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: local-path
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
    - patch: |-
        apiVersion: v1
        kind: Namespace
        metadata:
          name: local-path-storage
          labels:
            pod-security.kubernetes.io/enforce: privileged
