---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: traefik
  sourceRef:
    kind: GitRepository
    name: netcluster
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 1h
  path: ./kubernetes/apps/default/jellyfin/app
  prune: true
  # retryInterval: 2m
  # timeout: 5m
  # wait: false
