---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: netcluster
  namespace: flux-system
spec:
  url: https://github.com/kbujari/infra.git
  interval: 30m
  ref:
    branch: master
  ignore: |
    /*
    !/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/flux/config
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: netcluster
