---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitwarden-sm
spec:
  interval: 30m
  chart:
    spec:
      chart: sm-operator
      version: "0.1.0-Beta"
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
