machine:
  features:
    hostDNS:
      enabled: true
      resolveMemberNames: true
      forwardKubeDNSToHost: false
  kubelet:
    extraMounts:
      - type: bind
        destination: &path /var/lib/longhorn
        source: *path
        options:
          - bind
          - rshared
          - rw
  network:
    nameservers:
      - 9.9.9.9
      - 149.112.112.112
    interfaces:
      - interface: eth0
        dhcp: true
        mtu: 9000
        # vip:
        #   ip: 192.168.2.12

  install:
    diskSelector:
      type: nvme
    image: factory.talos.dev/installer/ebdfa27a8d6272acf806ac6a5c968c3c284a47ce880273cecb19442c11bf0474:v1.7.6
    extraKernelArgs:
      - mitigations=off
      - talos.platform=metal
      - net.ifnames=0
  files:
    - content: |-
        [ NFSMount_Global_Options ]
        nfsvers=4.2
        hard=True
        noatime=True
        nodiratime=True
        rsize=131072
        wsize=131072
        nconnect=8
      permissions: 420
      path: /etc/nfsmount.conf
      op: overwrite
  udev:
    rules:
      # GPU
      - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660"

cluster:
  allowSchedulingOnControlPlanes: true
  proxy:
    disabled: true
  network:
    cni:
      name: none
    podSubnets:
      - 10.244.0.0/16
